syntax = "proto3";

package register.v1;

option go_package = "app/internal/gen/register/v1;registerv1";

import "buf/validate/validate.proto";
import "health/v1/health.proto";

service RegisterDataNode {
  rpc RegisterDataNode(RegisterDataNodeRequest) returns (RegisterDataNodeResponse);
}

message RegisterDataNodeRequest {
  string node_id = 1;
  string hostname = 2;
  uint32 port = 3 [(buf.validate.field).uint32.lte = 65535];
  string scheme = 4 [(buf.validate.field).string = { in: ["grpc", "grpcs"] }];
  health.v1.HealthSnapshot health_snapshot = 5;
}

message RegisterDataNodeResponse {}
