import env from '@/env';

/**/

export const DEFAULT_GRPC_DEADLINE_MS = 5000;
export const GRPC_BLOB_MESSAGE_OVERHEAD_BYTES = 1024 * 1024;
export const GRPC_BLOB_MESSAGE_SIZE_LIMIT_BYTES = env.BLOB_SIZE_LIMIT_BYTES + GRPC_BLOB_MESSAGE_OVERHEAD_BYTES;
